### Send POST Command - Create Restaurant
POST http://localhost:8080/commands
Content-Type: application/json

{
  "type": "com.fraktalio.domain.CreateRestaurantCommand",
  "identifier": "10fca0c4-3376-4ca2-a7c2-db2b75c250a1",
  "name": "Big Snack",
  "menu": {
    "menuId": "10fca0c4-3376-4ca2-a7c2-db2b75c250a2",
    "cuisine": "SERBIAN",
    "menuItems": [
      {
        "menuItemId": "10fca0c4-3376-4ca2-a7c2-db2b75c250a3",
        "name": "Cevapi",
        "price": 300
      },
      {
        "menuItemId": "10fca0c4-3376-4ca2-a7c2-db2b75c250a4",
        "name": "Pljeskavica",
        "price": 400
      }
    ]
  }
}

### Send POST Command - Place the Order
POST http://localhost:8080/commands
Content-Type: application/json

{
  "type": "com.fraktalio.domain.PlaceOrderCommand",
  "identifier": "10fca0c4-3376-4ca2-a7c2-db2b75c250a1",
  "orderIdentifier": "10fca0c4-3376-4ca2-a7c2-db2b75c250a5",
  "lineItems": [
    {
      "id": "10fca0c4-3376-4ca2-a7c2-db2b75c250a6",
      "menuItemId": "10fca0c4-3376-4ca2-a7c2-db2b75c250a3",
      "name": "Cevapi",
      "quantity": 10
    },
    {
      "id": "10fca0c4-3376-4ca2-a7c2-db2b75c250a7",
      "menuItemId": "10fca0c4-3376-4ca2-a7c2-db2b75c250a4",
      "name": "Pljeskavica",
      "quantity": 1
    }
  ]
}

### Send POST Command - Mark order as Prepared
POST http://localhost:8080/commands
Content-Type: application/json

{
  "type": "com.fraktalio.domain.MarkOrderAsPreparedCommand",
  "identifier": "10fca0c4-3376-4ca2-a7c2-db2b75c250a5"
}

### GET all restaurants
GET http://localhost:8080/restaurants

### GET all orders
GET http://localhost:8080/orders


